config/routes.rb
Rails.application.routes.draw do
  get 'groups/show'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :groups, only: [:index, :new, :create ] do
    resources :expenses, only: [:index, :new, :create]
  end

  get 'static_pages/splash_page'

  authenticated :user do
    root :to => 'groups#index', as: :authenticated_root
  end

  root to: "static_pages#splash_page"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :groups

  validates :name, presence: { strict: true }
  validates :amount, presence: { strict: true }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :expenses

  def sum
    amount = 0
    expenses.each do |expense|
      amount += expense.amount
    end
    amount.to_i
  end

  validates :name, presence: { strict: true }
  validates :icon, presence: { strict: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, foreign_key: 'author_id'
  has_many :expenses, foreign_key: 'author_id'

  validates :name, presence: { strict: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @group = current_user.groups.find(params[:group_id])
    @expenses = @group.expenses.order(created_at: :desc)
    @img = @group.icon
  end

  def new
    @expense = Expense.new
    @groups = current_user.groups.all
    @group = @groups.find(params[:group_id])
  end

  def create
    @group = Group.find(params[:group_id])
    @expense = current_user.expenses.new(expense_params)
    respond_to do |format|
      if @expense.save
        redirect_to group_expenses_path
        return
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def expense_params
    params.require(:expense).permit(:name, :amount, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
    # @expenses = @group.expenses
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)
    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy; end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:splash_page]

  def splash_page; end

  def dashboard; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    bootstrap_alert_class = {
      'success' => 'alert-success',
      'error' => 'alert-danger',
      'notice' => 'alert-info',
      'alert' => 'alert-danger',
      'warn' => 'alert-warning'
    }
    bootstrap_alert_class[level]
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/expenses/index.html.erb
<%= render 'layouts/header' %>
<div id="page-container">
    <div class="container mt-2" id="content-wrap">
        <%= link_to "", groups_path, class:'fa-solid fa-arrow-left arrow'%>
        <div class="d-flex justify-content-between align-items-center border p-3 gap-5 mt-4 mb-4">
            <%= image_tag @group.icon, alt: 'icon', class: 'thumbnail' %>
            <div class="d-flex align-items-center justify-content-center gap-2">
                <h4>Total Money Spent :</h4>
                <b class="display-4"><%= @group.sum %>$</b>
            </div>
        </div>
        <div class="row mb-5 mt-5">
            <% @expenses.each do |expense| %>
                <div class="col-12">
                    <div class="card mt-3 mb-3">
                        <div class="card-body d-flex flex-row justify-content-between align-items-center">
                            <div class="d-flex flex-row justify-content-center align-items-center gap-5">
                                <div class="align-items-center">
                                    <h4><%= expense.name %></h4>
                                    <p><%= (expense.created_at).to_fs(:short) %></p>
                                </div>
                            </div>
                            <p class='display-4'><%= (expense.amount).to_i %>$</p>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
<div class="new-bar">
    <%= link_to "New Transaction" ,new_group_expense_path(@group.id) %>
</div>
</div>

app/views/expenses/new.html.erb
<%= render 'layouts/header' %>
<%= link_to "", groups_path, class:'fa-solid fa-arrow-left arrow'%>
<h1 class="d-flex justify-content-center mt-3">Add a new expense </h1>
<%= form_with model: @expense, url: group_expenses_path(@group.id), local: true, scope: :expense do |f| %>    
    <div class="form-group m-3">
        <%= f.label :name, class:"form-label" %>
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group m-3">
        <%= f.label :amount %>
        <%= f.number_field :amount, class: "form-control", step: 1, min: "0"  %>
    </div>
    <%= f.hidden_field :group_id, value: @group.id  %>
    <div class="d-flex justify-content-center">
        <%= f.submit "Add Expense", class: "btn btn-primary" %>
    </div>

<% end %>

app/views/groups/index.html.erb
<%= render 'layouts/header' %>
<div id="page-container">
  <div class="container mt-2" id="content-wrap">
    <%= link_to "", root_path, class:'fa-solid fa-arrow-left arrow'%>
    <div class="row mb-5 mt-5">
      <% @groups.each do |group| %>
          <div class="col-12">
            <div class="card mt-3">
              <div class="card-body d-flex flex-row justify-content-between align-items-center">
                <div class="d-flex flex-row align-items-center gap-4">
                  <%= image_tag group.icon, alt: 'icon', class: 'thumbnail' %>
                  <div class="align-items-center">
                  <%= link_to group_expenses_path(group.id), class: "anchor" do %>
                    <h5 class="card-title"><%= group.name %></h5>
                  <% end %>
                  <b>Created at :</b>
                  <p><%= (group.created_at).to_fs(:short) %></p>
                  </div>
                </div>
                <div>
                  <b>Amount: <%= group.sum %> $</b>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
  <div class="new-bar">
    <%= link_to "New Category", new_group_path %>
  </div>
</div>

app/views/groups/new.html.erb
<%= render 'layouts/header' %>
<%= link_to "", root_path, class:'fa-solid fa-arrow-left arrow'%>
<h1 class="d-flex justify-content-center mt-3">Add new Group</h1>
<%= form_with model: @group, url: groups_path, method: :post, local: true, scope: :group do |f| %>
    <div class="form-group m-3">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group m-3">
        <%= f.label :icon %>
        <%= f.text_field :icon, class: "form-control" %>
    </div>
    <div class="d-flex justify-content-center">
        <%= f.submit "Create Group", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark p-3 d-flex justify-content-between">
    <%= link_to "Money Manager", root_path, class:"navbar-brand" %>
    <ul class="navbar-nav d-flex justify-content-between">
      <li class="nav-item m-auto">
        <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link'  %>
      </li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Money Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/eb9ab0d66a.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link href="http://fonts.cdnfonts.com/css/proxima-nova-2" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% if notice %>
      <% flash.each do |key, message| %>
        <div class="alert <%= flash_class(key) %> alert-dismissible fade show text-center" role="alert">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </body>
</html>

app/views/static_pages/splash_page.html.erb
<div class="layouts">
  <div class="parent">
      <div class="card" id="leftToRight">
          <h2>Money Manager</h2>
          <div class="buttons">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-primary" %>
            <%= link_to "Register", new_user_registration_path, class: "btn btn-secondary"  %>
          </div>
      </div>
  </div>
</div>